name: CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  style-python:
    name: "💄 Style: python"
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin@v5.6.0
        with:
          python-version: "3.10"

      - name: Install style check dependencies
        run: |
          pip install flake8==6.0.0
          pip install pep8-naming==0.13.2

      - name: Check style
        run: |
          flake8 .

  style-js:
    name: "💄 Style: js"
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin@v4.4.0
        with:
          node-version: "23"

      - name: Install dependencies
        run: cd inventree_template_editor/frontend && npm ci

      - name: Check style
        run: cd inventree_template_editor/frontend && npm run lint

  build-js:
    name: "🏗️ Build: js"
    needs: [style-js]
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # pin@v4.4.0
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd inventree_template_editor/frontend && npm ci

      - name: Build js
        run: cd inventree_template_editor/frontend && npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # pin@v4.6.2
        with:
          name: frontend
          path: inventree_template_editor/static/dist

  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [style-python, build-js]
    name: 📦 Publish to PyPi
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/inventree-template-editor-plugin
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2

      - name: Setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin@v5.6.0
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: pip install --upgrade wheel setuptools twine build

      - name: Download frontend artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # pin@v4.3.0
        with:
          name: frontend
          path: inventree_template_editor/static/dist

      - name: Build pip package
        run: python3 -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # pin@v1.12.4
